language: node_js
node_js:
- "8"
notifications:
  slack:
    secure: be5ll7WycvVASiDo3KHSqamevE5ZCb2IL0CHdQsWAHwc7Hf7l+ayyH5I7cmMk4XqKiq0hsQpP2Dpxnk7ZENKMdV8o1cyv0q17uXVhjdMJsODI18Td9dYIjxkz+LZ8xzflgTPHDdug27d0pcGU6HwK75Z7XecPKbKoSQn89DuXG9OwXHusUALWUPZqe65v4a1VZoNyJa8bew3q7b8bU3z8drA5DZ1cZ1Ptv0hsYd+DX8Bn6T+LWsxNjKiVZXqiTUP4akSmi+VvMRdsQkEyJmv/YDiCFtdDYbCqe1FeY2WThpoXRTvNXjurH8i5TY1lnkYQQbhVig/Sc+QfEGVMvRb39RFVQlbEclrB7AykpYJq8aLHlAbv5m13vhvpnU4bxsVhz5pD6jxOaaoU1Fz+uRttEJkNPLZTJ8VVpLnMpYMmli+x+lNBQZDlLb/7Bt/lE3S4sVV+2zO/b2E1PcJKY8SpoWJ/bvRXoZbJUS8zgPCq0e+15f8MV01mQHonA3OV32CGzmt/gFp3M6eNEa42DSVqlFk3WRNbBMLQcQalIlul16/SYFOSeLK4L5UfMxDfrBjkGXAM3C2KzeVFYCJa2sZb4NIR0X5howjCCIitZX91Rzvkf4/I1p28tEcnY5bc3yeljiJbf4XKHB5gTm5JTmxm4Vx7mf/izXoBM15ap1U/34=
